title: Uploading weather data to Weather Underground
hero_image: images/banner.png
description: Upload your climate measurements to Weather Underground
original_url:
theme: orange
duration: 2
listed: false
ingredient: false
copyedit: false
interests: "weather"
technologies: "web"
curriculum: creator
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Registering with Weather Underground
  - title: The Weather Underground upload protocol
  - title: Using Python to convert your data
  - title: Using Python to upload your data
  - title: Using live data
  - title: Challenge -  Weather Underground widgets
