title: Uploading weather data to Weather Underground
hero_image: images/banner.png
description: Upload your own climate measuremets to Weather Underground
original_url:
theme: orange
duration: 2
listed: false
ingredient: false
copyedit: false
interests: "weather"
technologies: "web"
curriculum: creator
site_areas:
steps:
  - title: "Introduction"
  - title: "What you will need"
  
